// @ts-check

/**
 * All notes in reading order (01 → 22).
 * Update this list by hand when you add a new note file.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  notes: [
    { type: 'autogenerated', dirName: '.' },
  ],
};

module.exports = sidebars;
